### ISSUE TITLE
Class-aware detection

### ISSUE THREAD

**Issue by luckychay** [mmaaz60/mdef_detr#2]
hello , I want to change the model into an class-aware detector, whichi part should I modify? Thank you !

**Comment by mmaaz60** [comment]
Hi @luckychay,

MDef-DETR is developed to be a class-agnostic Object Detector. However, you may use targeted text queries to detect a specific class in your case. For example, using `every dog` query should provide you `dog` bounding boxes and so on.

**Comment by luckychay** [comment]
Hi, @mmaaz60. Thank you for you reply!  Your  answer partly solved my question. But in fact, I am asking about MDef-DETR  minus language, sorry for not clarifying my question. Finally I find the postprocessor should be changed for my needs. But I came into another question.

I am intersted in  MDef-DETR  minus language mainly due to my project needs Coco2017 and Pascal Voc 2012 as the training dataset. While MDef-DETR uses Coco2014 and Refcoco/+/g as the annotations, it seems not suitable for me to use MDef-DETR because there is no exsiting reference datasets for Coco2017 and Voc 2012.  

So my question is, do you have any suggestions for me if I need to use MDef-DETR for better performance?

**Comment by mmaaz60** [comment]
Hi @luckychay,

My apologies for the delayed response. `MDef-DETR minus language` is equivalent to standard [Def-DETR](https://github.com/fundamentalvision/Deformable-DETR) model. If you are only working with COCO or VOC datasets which don't have any language/language structure, then using Def-DETR might be good for you. Please let me know if you have any questions.

Thanks

**Comment by luckychay** [comment]
Hello @mmaaz60,

Never mind. I understand better now but I do have another question. How can I use COCO or VOC to train or finetune MDef-DETR if they don't have any language\language structure？ Should I add an empty caption for every image? 

Thank you!

**Comment by mmaaz60** [comment]
Hi @luckychay,

Apologies for the delayed reply. We could use Def-DETR model for training on COCO and VOC model as it does not require any language component. However, exploration of synthesizing language structure for standard detection dataset would be a good research direction to explore.

In table 9 of our [paper](https://arxiv.org/pdf/2111.11430.pdf), we show that randomly grouping 4-8 bounding boxes to synthesize language structure is not helpful. However, exploring cues such as super vs child class relationship and vicinity to group similar boxes/objects could be good research direction to explore.

Please let me know if you have any questions.

**Comment by luckychay** [comment]
Ok, that makes sense. You are really patient. Thanks a lot!
